import LandingPageHeader from '@/components/home-header';
import { Button } from '@/components/ui/button';
import { SignInButton } from '@clerk/nextjs';
import { Metadata } from 'next';
import PreviewImage from './preview-image';

export const metadata: Metadata = {
  title: 'SnippetHub - Your go-to code snippet manager',
  description: 'Generated by create next app',
};

export default async function Home() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-between bg-background text-text px-6 py-12">
      <LandingPageHeader />

      {/* Hero Section */}
      <div className="text-center max-w-3xl mt-24">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
          <span className="text-primary">SnippetHub</span> your go-to code
          snippet manager
        </h1>
        <p className="mt-4 text-md text-muted-foreground">
          Organize, save, and share your code snippets effortlessly with a
          seamless developer-friendly experience.
        </p>
      </div>

      {/* CTA Image Section */}
      <div className="mt-12 w-full max-w-4xl text-center">
        <PreviewImage />
        <p className="mt-6 text-lg font-medium">
          Start organizing your snippets today!
        </p>
        <SignInButton mode="modal">
          <Button className="mt-4 px-6 py-3 text-md">Try SnippetHub</Button>
        </SignInButton>
      </div>
    </div>
  );
}
